#FROM mariadb:10.5.9
#CMD ["mysqld", "--read-buffer-size=16M", "--innodb-buffer-pool-size=16G", "--innodb_log_file_size=2G", "--net-read-timeout=600", "--net-write-timeout=600", "--key-buffer=128M", "--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--max-allowed-packet=500M", "--wait-timeout=2147483", "--interactive-timeout=2147483", "--log-warnings=4", "--open-files-limit=100000", "--connect-timeout=30", "--slave-net-timeout=3600"]
#CMD mysql -u root -p secret ignis < ignis.sql
#EXPOSE 3306